//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel.DescriptionOfTask.Tool
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Shape;
    using System.Drawing;
	public static class ToolsVM
	{
        
        public static LineVM Line(Point MidPoint)
        {
             return new LineVM(MidPoint); 
        }
        public static EllipseVM Ellipse(Point MidPoint)
        {
            return new EllipseVM(MidPoint); 
        }
	}
}

