//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ViewModel.DescriptionOfTask.Tool.Shape
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Shapes;
    using System.Drawing;
	public class EllipseVM
	{
        public Ellipse Ellipse;
        public EllipseVM(PointF MidPoint)
        {
            Ellipse = new Ellipse();
            Ellipse.Width = 100;
            Ellipse.Height = 100;
            Ellipse.Margin = new System.Windows.Thickness(MidPoint.X, MidPoint.Y, 0, 0);

        }
	}
}

