//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model.Tool.Shape
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;
	public class EllipseM
	{
        public EllipseM(PointF midPoint)
        {
            MiddlePoint = midPoint;
            //Wight = 100;
            //Height = Wight / 2;
        }
        public EllipseM(PointF midPoint, int Wight, int Height)
        {
            _midPoint = midPoint;
            this.Wight = Wight;
            this.Height = Height;
        }
        public int Wight { get; set; }
        public int Height { get; set; }

        private PointF _midPoint;
        public PointF MiddlePoint
        {
            get { return _midPoint; }
            private set { _midPoint = value; }
        }

	}
}

