//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model.Tool.Shape
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;
    
	public class LineM
	{
        public LineM(PointF midPoint)
        {
            MiddlePoint = midPoint;
        }


        private PointF _p1;
        private PointF _p2;
        public PointF P1
        {
            get { return _p1; }
        }
        public PointF P2
        {
            get { return _p2; }
        }

        private PointF _midPoint;
        public PointF MiddlePoint
		{
            get { return _midPoint; }
            private set { _midPoint = value; }
		}
        

        

	}
}

