//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model.Tool.Shape
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PointM
	{
        public int X { get; set; }
        public int Y { get; set; }

        public PointM(int x, int y)
        {
            X = x;
            Y = y;
        }
	}
}

